package arraylist;

import java.awt.Image;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class VentanaBuscarAlumno extends javax.swing.JFrame {

    //BASE DATOS
    List<Alumno> alumnos_al = new ArrayList<>();
    DefaultListModel<String> modeloLista = new DefaultListModel<>(); //se encarga de poner elementos a la lista de asignaturas
    ButtonGroup edad = new ButtonGroup();

    public VentanaBuscarAlumno() {
        initComponents();
        personalizarVentana();
        anadirPorDefecto();
        lstAsignaturas.setModel(modeloLista); //asignar el modelo a nuestra lista
        lstAsignaturasID.setModel(modeloLista);
        cmdBuscarNombre.setEnabled(true);
        edad.add(rdoMENOR);
        edad.add(rdoMAYOR);
    }

    public void llenarComboBox() {
        for (int i = 1; i <= 100; i++) {
            txaNavegarXAlumno.addItem(i + "");
        }
    }

    public void anadirPorDefecto() {
        List<String> asignaturas1_al = new ArrayList<>();
        asignaturas1_al.add("Física");
        asignaturas1_al.add("Química");
        Alumno alumno1 = new Alumno("A1", "Luis", "Roncal", 15, asignaturas1_al);

        Alumno alumno2 = new Alumno("A2", "Miguel", "Alva", 17, new ArrayList<>(Arrays.asList("Religión", "Matemática", "Física", "Química")));
        Alumno alumno3 = new Alumno("A3", "Luis", "Zuñiga", 18, new ArrayList<>(Arrays.asList("Literatura", "Matemática", "Física", "Química")));
        Alumno alumno4 = new Alumno("A4", "Carmen", "Cuba", 19, new ArrayList<>(Arrays.asList("Arte", "Matemática", "Física", "Química")));
        Alumno alumno5 = new Alumno("A5", "María", "Rodriguez", 18, new ArrayList<>(Arrays.asList("Arte", "Matemática", "Física", "Química")));
        Alumno alumno6 = new Alumno("A6", "Arturo", "Alcantara", 17, new ArrayList<>(Arrays.asList("Arte", "Matemática", "Química")));
        Alumno alumno7 = new Alumno("A7", "Ismael", "Lescano", 16, new ArrayList<>(Arrays.asList("Arte", "Matemática", "Historia", "Laboral")));
        Alumno alumno8 = new Alumno("A8", "Julieta", "Jauregui", 15, new ArrayList<>(Arrays.asList("Arte", "Matemática", "Ciencias Naturales", "Laboral")));
        Alumno alumno9 = new Alumno("A9", "Silvia", "Jauregui", 15, new ArrayList<>(Arrays.asList("Arte", "Biología", "Ciencias Naturales", "Laboral")));
        Alumno alumno10 = new Alumno("A10", "Luis", "Párraga", 16, new ArrayList<>(Arrays.asList("Arte", "Biología", "Historia", "Laboral")));

        alumnos_al.add(alumno1);
        alumnos_al.add(alumno2);
        alumnos_al.add(alumno3);
        alumnos_al.add(alumno4);
        alumnos_al.add(alumno5);
        alumnos_al.add(alumno6);
        alumnos_al.add(alumno7);
        alumnos_al.add(alumno8);
        alumnos_al.add(alumno9);
        alumnos_al.add(alumno10);
    }

    public void personalizarVentana() {
        ImageIcon icono = new ImageIcon("image/cross1.png");
        Image image = icono.getImage();
        this.setIconImage(image); // cambiar el icono de la ventana

        //this.setSize(350, 250);  //poner un ancho y alto a la ventana
        this.setResizable(false);  // no es redimensione
        this.setLocationRelativeTo(null); //colocar la ventana en el centro de ka pantalla
        //this.setVisible(true);  // mostrar la ventana ************
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        popupMenu1 = new java.awt.PopupMenu();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        txaNavegarXAlumno = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblBuscarNombreID = new javax.swing.JLabel();
        txtBuscarIdAlumno = new javax.swing.JTextField();
        cmdBuscarID = new javax.swing.JButton();
        botNuevo1 = new javax.swing.JButton();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jTextEdad = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstAsignaturasID = new javax.swing.JList<>();
        TxtTodo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaMostrar = new javax.swing.JTextArea();
        txtBuscarNombre = new javax.swing.JTextField();
        lblBuscarNombre = new javax.swing.JLabel();
        cmdBuscarNombre = new javax.swing.JButton();
        botNuevo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstAsignaturas = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        lblAsignatura = new javax.swing.JLabel();
        txtAsignatura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMostrarAlumnosXasignatura = new javax.swing.JTextArea();
        cmdBuscarAlumnosXasignaturas = new javax.swing.JButton();
        cmdNuevoAlumnosXasignaturas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cboSeleccionarID = new javax.swing.JComboBox<>();
        txtIdAlumnoComboBox = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        rdoMENOR = new javax.swing.JRadioButton();
        rdoMAYOR = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaMostrarEdades = new javax.swing.JTextArea();
        cmdNuevo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBuscarNombreID.setText("INGRESAR IDALUMNO ");

        txtBuscarIdAlumno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscarIdAlumno.setText("luis");
        txtBuscarIdAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarIdAlumnoActionPerformed(evt);
            }
        });

        cmdBuscarID.setText("BUSCAR");
        cmdBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarIDActionPerformed(evt);
            }
        });

        botNuevo1.setText("NUEVO");
        botNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botNuevo1ActionPerformed(evt);
            }
        });

        jTextEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEdadActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(lstAsignaturasID);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtTodo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblBuscarNombreID)
                                .addGap(47, 47, 47)
                                .addComponent(txtBuscarIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(132, 132, 132)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdBuscarID)
                            .addComponent(botNuevo1))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBuscarNombreID)
                        .addComponent(txtBuscarIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmdBuscarID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botNuevo1)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        txaNavegarXAlumno.addTab("ID", jPanel1);

        txaMostrar.setEditable(false);
        txaMostrar.setColumns(20);
        txaMostrar.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txaMostrar.setForeground(new java.awt.Color(153, 0, 51));
        txaMostrar.setRows(5);
        jScrollPane2.setViewportView(txaMostrar);

        txtBuscarNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarNombreActionPerformed(evt);
            }
        });

        lblBuscarNombre.setText("BUSCAR POR NOMBRE");

        cmdBuscarNombre.setText("BUSCAR");
        cmdBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarNombreActionPerformed(evt);
            }
        });

        botNuevo.setText("NUEVO");
        botNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botNuevoActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(lstAsignaturas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblBuscarNombre)
                        .addGap(82, 82, 82)
                        .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cmdBuscarNombre)
                                .addGap(58, 58, 58)
                                .addComponent(botNuevo))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscarNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botNuevo)
                            .addComponent(cmdBuscarNombre)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        txaNavegarXAlumno.addTab("NOMBRE", jPanel4);

        lblAsignatura.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblAsignatura.setText("INGRESAR ASIGNATURA");

        txtAsignatura.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtAsignatura.setForeground(new java.awt.Color(102, 0, 204));
        txtAsignatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAsignaturaActionPerformed(evt);
            }
        });

        txaMostrarAlumnosXasignatura.setColumns(20);
        txaMostrarAlumnosXasignatura.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txaMostrarAlumnosXasignatura.setRows(5);
        jScrollPane1.setViewportView(txaMostrarAlumnosXasignatura);

        cmdBuscarAlumnosXasignaturas.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cmdBuscarAlumnosXasignaturas.setText("BUSCAR");
        cmdBuscarAlumnosXasignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarAlumnosXasignaturasActionPerformed(evt);
            }
        });

        cmdNuevoAlumnosXasignaturas.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cmdNuevoAlumnosXasignaturas.setText("NUEVO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(cmdBuscarAlumnosXasignaturas)
                .addGap(123, 123, 123)
                .addComponent(cmdNuevoAlumnosXasignaturas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(txtAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsignatura)
                    .addComponent(txtAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdNuevoAlumnosXasignaturas)
                    .addComponent(cmdBuscarAlumnosXasignaturas))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        txaNavegarXAlumno.addTab("ALMNOS POR ASIGNATURA", jPanel5);

        cboSeleccionarID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSeleccionarIDItemStateChanged(evt);
            }
        });
        cboSeleccionarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSeleccionarIDActionPerformed(evt);
            }
        });

        txtIdAlumnoComboBox.setEditable(false);
        txtIdAlumnoComboBox.setForeground(new java.awt.Color(0, 255, 51));
        txtIdAlumnoComboBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(cboSeleccionarID, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(txtIdAlumnoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSeleccionarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdAlumnoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        txaNavegarXAlumno.addTab("ID COMBOBOX", jPanel3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        txaNavegarXAlumno.addTab("EDAD", jPanel6);

        rdoMENOR.setText("MENOR");
        rdoMENOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMENORActionPerformed(evt);
            }
        });

        rdoMAYOR.setText("MAYOR");
        rdoMAYOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMAYORActionPerformed(evt);
            }
        });

        txaMostrarEdades.setColumns(20);
        txaMostrarEdades.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txaMostrarEdades.setForeground(new java.awt.Color(204, 0, 204));
        txaMostrarEdades.setRows(5);
        jScrollPane5.setViewportView(txaMostrarEdades);

        cmdNuevo.setText("NUEVO");
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(rdoMENOR, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(rdoMAYOR, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(cmdNuevo)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoMENOR)
                    .addComponent(rdoMAYOR))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdNuevo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txaNavegarXAlumno.addTab("EDADRADIOBUTTON", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        txaNavegarXAlumno.addTab("NAVEGAR X ALUMNO", jPanel8);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setText("BUSCAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(txaNavegarXAlumno, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txaNavegarXAlumno)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarNombreActionPerformed
        // TODO add your handling code here:

        String nombre = txtBuscarNombre.getText();
        List<Alumno> alumnosaux_al = obtenerListaNombres(nombre);
        if (alumnosaux_al.size() > 0) {
            Alumno.cabecera();
            txaMostrar.append(Alumno.cabecera());
            txaMostrar.append(Alumno.Subrrayadocabecera());
            for (Alumno a : alumnosaux_al) {
                // txaMostrar.append(a.toString() + "\n");
                txaMostrar.append(a.cuerpo());
                List<String> asignaturas_al = a.getAsignaturas_al();
                for (String s : asignaturas_al) {
                    modeloLista.addElement(s);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "NO EXISTE ALUMNOS CON DICHO NOMBRE", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_txtBuscarNombreActionPerformed

    private void cmdBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarNombreActionPerformed
        String nombre = txtBuscarNombre.getText();
        List<Alumno> alumnosaux_al = obtenerListaNombres(nombre);
        if (alumnosaux_al.size() > 0) {
            Alumno.cabecera();
            txaMostrar.append(Alumno.cabecera());
            txaMostrar.append(Alumno.Subrrayadocabecera());
            for (Alumno a : alumnosaux_al) {
                // txaMostrar.append(a.toString() + "\n");
                txaMostrar.append(a.cuerpo());
                List<String> asignaturas_al = a.getAsignaturas_al();
                for (String s : asignaturas_al) {
                    modeloLista.addElement(s);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "NO EXISTE ALUMNOS CON DICHO NOMBRE", "Error", JOptionPane.ERROR_MESSAGE);
        }
        cmdBuscarNombre.setEnabled(false);
    }//GEN-LAST:event_cmdBuscarNombreActionPerformed

    private void botNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botNuevoActionPerformed
        txtBuscarNombre.setText("");        // TODO add your handling code here:
        txaMostrar.setText(""); // para el boton nuevo limpia
        modeloLista.clear();

        String nombre = txtBuscarNombre.getText();
        List<Alumno> alumnosaux_al = obtenerListaNombres(nombre);
        if (alumnosaux_al.size() > 0) {
            Alumno.cabecera();
            txaMostrar.append(Alumno.cabecera());
            txaMostrar.append(Alumno.Subrrayadocabecera());
            for (Alumno a : alumnosaux_al) {
                // txaMostrar.append(a.toString() + "\n");
                txaMostrar.append(a.cuerpo());
            }

        } else {
            JOptionPane.showMessageDialog(null, "NO EXISTE ALUMNOS CON DICHO NOMBRE", "Error", JOptionPane.ERROR_MESSAGE);
        }
        cmdBuscarNombre.setEnabled(false);

    }//GEN-LAST:event_botNuevoActionPerformed

    private void txtBuscarIdAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarIdAlumnoActionPerformed
        String nombre = txtBuscarNombre.getText();
        List<Alumno> alumnosaux_al = obtenerListaNombres(nombre);
        if (alumnosaux_al.size() > 0) {
            Alumno.cabecera();
            txaMostrar.append(Alumno.cabecera());
            txaMostrar.append(Alumno.Subrrayadocabecera());
            for (Alumno a : alumnosaux_al) {
                // txaMostrar.append(a.toString() + "\n");
                txaMostrar.append(a.cuerpo());
                List<String> asignaturas_al = a.getAsignaturas_al();
                for (String s : asignaturas_al) {
                    modeloLista.addElement(s);
                }
            }
        }
    }//GEN-LAST:event_txtBuscarIdAlumnoActionPerformed

    private void cmdBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarIDActionPerformed
        txaMostrar.setText("");
        String nombre = txtBuscarNombre.getText();
        List<Alumno> alumnosaux_al = obtenerListaNombres(nombre);
        if (alumnosaux_al.size() > 0) {
            Alumno.cabecera();
            txaMostrar.append(Alumno.cabecera());
            txaMostrar.append(Alumno.Subrrayadocabecera());
            for (Alumno a : alumnosaux_al) {
                // txaMostrar.append(a.toString() + "\n");
                txaMostrar.append(a.cuerpo());
                List<String> asignaturas_al = a.getAsignaturas_al();
                for (String s : asignaturas_al) {
                    modeloLista.addElement(s);
                    for (String asi : asignaturas_al) {
                        modeloLista.addElement(asi);
                    }

                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "NO EXISTE ALUMNOS CON DICHO NOMBRE", "Error", JOptionPane.ERROR_MESSAGE);
        }
        cmdBuscarNombre.setEnabled(false);
    }//GEN-LAST:event_cmdBuscarIDActionPerformed

    private void botNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botNuevo1ActionPerformed
        txtBuscarNombre.setText("");        // TODO add your handling code here:
        txaMostrar.setText(""); // para el boton nuevo limpia
        modeloLista.clear();

        String nombre = txtBuscarNombre.getText();
        List<Alumno> alumnosaux_al = obtenerListaNombres(nombre);
        if (alumnosaux_al.size() > 0) {
            Alumno.cabecera();
            txaMostrar.append(Alumno.cabecera());
            txaMostrar.append(Alumno.Subrrayadocabecera());
            for (Alumno a : alumnosaux_al) {
                // txaMostrar.append(a.toString() + "\n");
                txaMostrar.append(a.cuerpo());
            }

        } else {
            JOptionPane.showMessageDialog(null, "NO EXISTE ALUMNOS CON DICHO NOMBRE", "Error", JOptionPane.ERROR_MESSAGE);
        }
        cmdBuscarNombre.setEnabled(false);
    }//GEN-LAST:event_botNuevo1ActionPerformed

    private void jTextEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEdadActionPerformed

    private void txtAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsignaturaActionPerformed

    private void cmdBuscarAlumnosXasignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarAlumnosXasignaturasActionPerformed
        // TODO add your handling code here:
        String asignatura = txtAsignatura.getText().toLowerCase().trim(); //trim limpiar los espacios delante o detras
        int encontrado = 0;
        int i = 0;
        for (Alumno a : alumnos_al) { //aqui busta el listado

            List<String> asignaturas_al = a.getAsignaturas_al(); // Genera la lista de asignaturas y las imprime
            for (String asig : asignaturas_al) {
                if (asig.toLowerCase().equals(asignatura)) {
                    if (i == 0) {
                        txaMostrarAlumnosXasignatura.append(Alumno.cabecera());
                        txaMostrarAlumnosXasignatura.append(Alumno.Subrrayadocabecera());
                        i++;
                    }
                    txaMostrarAlumnosXasignatura.append(a.cuerpo());
                    encontrado++;
                    break;
                }

            }

            // txaMostrarAlumnosXasignatura.append(Alumno.cabecera());
            // txaMostrarAlumnosXasignatura.append(Alumno.Subrrayadocabecera());
        }
        if (encontrado == 0) {
            JOptionPane.showMessageDialog(null, "ALUMNO NO EXISTE", "Error", JOptionPane.ERROR_MESSAGE);
        }
        cmdBuscarAlumnosXasignaturas.setEnabled(false);
    }//GEN-LAST:event_cmdBuscarAlumnosXasignaturasActionPerformed

    private void cboSeleccionarIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSeleccionarIDItemStateChanged
        // TODO add your handling code here:
        String idAlumno = (String) cboSeleccionarID.getSelectedItem();
        txtIdAlumnoComboBox.setText(idAlumno);
    }//GEN-LAST:event_cboSeleccionarIDItemStateChanged

    private void cboSeleccionarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSeleccionarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSeleccionarIDActionPerformed

    private void rdoMENORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMENORActionPerformed
        txaMostrarEdades.setText("");
        for (Alumno a : alumnos_al) { //aqui llamamos a todos los alumnos
            if (a.getEdad() < 18) {
                txaMostrarEdades.append(a.cuerpo());

            }
        }
    }//GEN-LAST:event_rdoMENORActionPerformed

    private void rdoMAYORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMAYORActionPerformed
         txaMostrarEdades.setText("");    
        for (Alumno a : alumnos_al) { //aqui llamamos a todos los alumnos
            if (a.getEdad() >= 18) {
                txaMostrarEdades.append(a.cuerpo());

            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_rdoMAYORActionPerformed

    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed
       txaMostrarEdades.setText("");
    }//GEN-LAST:event_cmdNuevoActionPerformed

    public List<Alumno> obtenerListaNombres(String nombre) {
        List<Alumno> alumnosaux_al = new ArrayList<>();
        for (Alumno a : alumnos_al) {
            if (a.getNombre().toLowerCase().equals(nombre.toLowerCase())) { //para poner tanto en mayusculas como en minusculas
                alumnosaux_al.add(a);
            }
        }

        return alumnosaux_al;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscarAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtTodo;
    private javax.swing.JButton botNuevo;
    private javax.swing.JButton botNuevo1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cboSeleccionarID;
    private javax.swing.JButton cmdBuscarAlumnosXasignaturas;
    private javax.swing.JButton cmdBuscarID;
    private javax.swing.JButton cmdBuscarNombre;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JButton cmdNuevoAlumnosXasignaturas;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblBuscarNombre;
    private javax.swing.JLabel lblBuscarNombreID;
    private javax.swing.JList<String> lstAsignaturas;
    private javax.swing.JList<String> lstAsignaturasID;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JRadioButton rdoMAYOR;
    private javax.swing.JRadioButton rdoMENOR;
    private javax.swing.JTextArea txaMostrar;
    private javax.swing.JTextArea txaMostrarAlumnosXasignatura;
    private javax.swing.JTextArea txaMostrarEdades;
    private javax.swing.JTabbedPane txaNavegarXAlumno;
    private javax.swing.JTextField txtAsignatura;
    private javax.swing.JTextField txtBuscarIdAlumno;
    private javax.swing.JTextField txtBuscarNombre;
    private javax.swing.JTextField txtIdAlumnoComboBox;
    // End of variables declaration//GEN-END:variables
}
